- hosts: all
  gather_facts: false
  become: true

  roles:
    #- role: install-docker
    - role: clean-docker
    - role: create-network
    - role: launch-database
    - role: launch-app
    - role: launch-front
    - role: launch-proxy
  
  vars:
    ansible_user: "{{ ANSIBLE_USER }}"
    ansible_python_interpreter: /usr/bin/python3