- hosts: all
  gather_facts: false
  become: true

  roles:
    #- install-docker
    - create-network
    - launch-database
    - launch-app
    - launch-front
    - launch-proxy
  
  vars:
    ansible_user: "{{ ANSIBLE_USER }}"
    #ansible_python_interpreter: /usr/bin/python3