- hosts: all
  gather_facts: false
  become: true

  roles:
    #- role: install-docker
    - role: clean-docker
    - role: create-network
    - role: launch-database
    - role: launch-app
    #- role: launch-proxy
    - role: launch-front