- name: Launch app
  docker_container:
    name: "{{ APP_CONTAINER_NAME }}"
    image: "{{ DOCKERHUB_APP_IMAGE }}"
    networks:
      - name: "{{ NETWORK_NAME }}"
    env:
      DATABASE_URL: "{{ DATABASE_URL }}"
      DATABASE_USER: "{{ DATABASE_USER }}"
      DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"