version: '3.7'

services:
  database:
    image: "leondumestre/tp-devops-database:1.0"
    ports:
      - "5432:5432"
    networks:
      - "app-network"
    volumes:
      - "/home/leon/Documents/CPE/devops-ci-cd/TP1/database/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd

  backend:
      image: "leondumestre/tp-devops-backend:1.0"
      ports:
        - "8080:8080"
      networks:
        - "app-network"
      depends_on:
        - "database"
      environment:
        - DATABASE_URL=jdbc:postgresql://database:5432/db
        - DATABASE_USER=usr
        - DATABASE_PASSWORD=pwd

  httpd:
      image: "leondumestre/tp-devops-httpd:1.0"
      ports:
        - "80:80"
      networks:
        - "app-network"
      depends_on:
        - "backend"

networks:
    app-network: