- name: Launch database
  docker_container:
    name: database
    image: "leondumestre/tp-devops-database:1.0"
    networks:
      - name: app-network
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd