- name: Launch database
  docker_container:
    name: "{{ DATABASE_CONTAINER_NAME }}"
    image: "{{ DOCKERHUB_DATABASE_IMAGE }}"
    networks:
      - name: "{{ NETWORK_NAME }}"
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: "{{ DATABASE_USER }}"
      POSTGRES_PASSWORD: "{{ DATABASE_PASSWORD }}"