ANSIBLE_USER: centos

DATABASE_CONTAINER_NAME: database
APP_CONTAINER_NAME: backend
PROXY_CONTAINER_NAME: httpd
FRONT_CONTAINER_NAME: front

DATABASE_URL: "jdbc:postgresql://{{ DATABASE_CONTAINER_NAME }}:5432/db"
DATABASE_USER: usr
DATABASE_PASSWORD: pwd

NETWORK_NAME: app-network

DOCKERHUB_USERNAME: leondumestre
DOCKERHUB_APP_IMAGE: "{{ DOCKERHUB_USERNAME }}/tp-devops-backend:1.0"
DOCKERHUB_FRONT_IMAGE: "{{ DOCKERHUB_USERNAME }}/tp-devops-front:1.0"
DOCKERHUB_DATABASE_IMAGE: "{{ DOCKERHUB_USERNAME }}/tp-devops-database:1.0"
DOCKERHUB_PROXY_IMAGE: "{{ DOCKERHUB_USERNAME }}/tp-devops-httpd:1.1"
