name: CI devops - Deploy
on:
  workflow_run:
    workflows: 'CI devops - Image'
    branches:  main
    types: completed

jobs:
  deploy-on-ansible:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Deploy on Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: TP3/ansible/playbook-deploy.yml
          key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            leon.dumestre.takima.cloud
