name: CI devops - Deploy
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  deploy-on-ansible:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Deploy on Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: TP3/ansible/playbook-deploy.yml
          key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            leon.dumestre.takima.cloud

