name: CI devops - Deploy
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Deploy on Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: TP3/ansible/playbook-deploy.yml
          key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}

