name: CI devops - Deploy
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  deploy-on-ansible:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Deploy on Ansible
        run: ansible-playbook -i TP3/ansible/inventories/setup.yml TP3/ansible/playbook-deploy.yml

